services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      POSTGRES_HOST: db
    ports:
      - "3032:5432"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "db", "-h", "db"]
      interval: 10s
      timeout: 5s
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge
